apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi
rules:
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  - volumeattachments
  - volumeattachments/status
  - csinodes
  verbs:
  - list
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumes
  - events
  - nodes
  verbs:
  - list
  - watch
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi
subjects:
- kind: ServiceAccount
  name: csi
  namespace: default
